### ISSUE TITLE
Configure the height of the button layer

### ISSUE THREAD

**Issue by bircni** [lascic/UIOnboarding#14]
Hi - so i have this problem:
I only want to have the button at the bottom, not a text or other stuff, but the size around the button still is HUGE - could you fix this?
<img width="385" alt="Bildschirmfoto 2023-04-29 um 23 02 06" src="https://user-images.githubusercontent.com/75789103/235324106-9012cf3d-6608-46ac-a534-2667070f906c.png">

**Comment by lascic** [comment]
Hey, thanks for reaching out. If you only want to have the button at the bottom without the notice text or icon above it, please refer to issue #11 where this has been addressed and fixed.
I hope this is what you're aiming for based on your issue description. If not, let me know and we'll work towards a solution. Thank you.

**Comment by bircni** [comment]
Sorry - no this did not fix it 
I can remove the text but the huge lightgray view in which the button is doesnt get adjusted.
It should get smaller so it doesnt take up so much space even when there is no text

**Comment by lascic** [comment]
I quickly tested it and it does the desired outcome you described by leaving out ```textViewConfiguration```. Did you try that out? Make sure the package is updated to v2.0.1.
``` swift
// In UIOnboardingHelper.swift
extension UIOnboardingViewConfiguration {
    static func setUp() -> UIOnboardingViewConfiguration {
        .init(appIcon: UIOnboardingHelper.setUpIcon(),
              firstTitleLine: UIOnboardingHelper.setUpFirstTitleLine(),
              secondTitleLine: UIOnboardingHelper.setUpSecondTitleLine(),
              features: UIOnboardingHelper.setUpFeatures(),
              // textViewConfiguration: UIOnboardingHelper.setUpNotice(),
              buttonConfiguration: UIOnboardingHelper.setUpButton())
    }
}
```
